"""Material registry: one definition per material, used to

* write the BeamNG v1.5 ``*.materials.json`` files (vehicle folder + shared common folder), and
* create matching Principled-BSDF preview materials in Blender (for renders/thumbnails).

Texture references are (owner, file) pairs resolved to game paths.  Vanilla
textures that the official docs name explicitly are referenced by their game
path (see ``BUILTIN``) and never shipped.
"""
from __future__ import annotations

import os
from collections import OrderedDict
from dataclasses import dataclass, field

# folders inside the mod
FOLDERS = {
    "s13": "vehicles/s13_240sx",
    "s14": "vehicles/s14_240sx",
    "s1x": "vehicles/common/s1x_240sx",
}

# vanilla textures referenced by path (documented in the official material docs)
BUILTIN = {
    "nullmaskR": "/vehicles/common/nullcolormaskR.color.png",
    "orange_peel": "/vehicles/common/orange_peel_n.normal.png",
    "carbon_d": "/vehicles/common/carbonfiber_d.color.png",
    "carbon_n": "/vehicles/common/carbonfiber_n.normal.png",
    "leather_grain": "/vehicles/common/generic_mat_tex/detail_leather_grain_nm.normal.png",
    "leather": "/vehicles/common/generic_mat_tex/detail_leather_nm.normal.png",
    "headliner": "/vehicles/common/generic_mat_tex/detail_headliner_nm.normal.png",
    "carpet": "/vehicles/common/generic_mat_tex/detail_carpet_nm.normal.png",
}


def tex(owner, fname):
    """Game path of a texture generated into the mod."""
    return f"/{FOLDERS[owner]}/textures/{fname}"


@dataclass
class Mat:
    name: str
    owner: str = "s1x"                 # which materials.json it is written to
    color: tuple = (0.5, 0.5, 0.5)     # linear base colour factor
    rough: float = 0.5
    metal: float = 0.0
    clearcoat: float = 0.0
    cc_rough: float = 0.03
    kind: str = "solid"                # solid | paint | glass | glass_dmg | emissive | decal
    base_map: str | None = None        # game paths
    normal_map: str | None = None
    rough_map: str | None = None
    metal_map: str | None = None
    opacity_map: str | None = None
    ao_map: str | None = None
    emissive_map: str | None = None
    emissive: tuple | None = None      # emissive factor (rgb)
    nits: float = 0.0
    opacity: float = 1.0
    detail_normal: str | None = None
    detail_map: str | None = None
    detail_scale: tuple = (40, 40)
    detail_strength: float = 1.0
    double_sided: bool = False
    extra: dict = field(default_factory=dict)
    preview: tuple | None = None       # override preview colour (rgba)
    preview_tex: str | None = None     # local texture file for the preview (relative to the mod root)
    write: bool = True                 # False: glowMap key (generated by the game) - preview only

    # ------------------------------------------------------------------ json
    def stage0(self):
        s = OrderedDict()
        if self.kind == "paint":
            s["colorPaletteMap"] = BUILTIN["nullmaskR"]
            s["colorPaletteMapUseUV"] = 1
            s["instanceDiffuse"] = True
            s["clearCoatFactor"] = 1
            s["clearCoatRoughnessFactor"] = 1
            s["metallicFactor"] = 1
            s["roughnessFactor"] = 1
            s["detailNormalMap"] = BUILTIN["orange_peel"]
            s["detailNormalMapStrength"] = 0.3
            s["detailScale"] = [128, 64]
            s["normalDetailMapUseUV"] = 1
            if self.normal_map:
                s["normalMap"] = self.normal_map
            if self.ao_map:
                s["ambientOcclusionMap"] = self.ao_map
            s.update(self.extra)
            return s
        if self.base_map:
            s["baseColorMap"] = self.base_map
            if self.color != (1, 1, 1) and self.kind not in ("glass", "glass_dmg"):
                s["baseColorFactor"] = [*map(_r, self.color), 1]
        else:
            s["baseColorFactor"] = [*map(_r, self.color), 1]
        if self.normal_map:
            s["normalMap"] = self.normal_map
        if self.ao_map:
            s["ambientOcclusionMap"] = self.ao_map
        if self.rough_map:
            s["roughnessMap"] = self.rough_map
        else:
            s["roughnessFactor"] = _r(self.rough)
        if self.metal_map:
            s["metallicMap"] = self.metal_map
            s["metallicFactor"] = 1
        else:
            s["metallicFactor"] = _r(self.metal)
        if self.clearcoat:
            s["clearCoatFactor"] = _r(self.clearcoat)
            s["clearCoatRoughnessFactor"] = _r(self.cc_rough)
        if self.opacity_map:
            s["opacityMap"] = self.opacity_map
        elif self.kind in ("glass", "decal") and self.opacity < 1:
            s["opacityFactor"] = _r(self.opacity)
        if self.kind == "emissive":
            s["emissiveFactor"] = [*map(_r, self.emissive or (1, 1, 1))]
            s["emissiveIntensityNits"] = self.nits
            if self.emissive_map:
                s["emissiveMap"] = self.emissive_map
        if self.detail_normal:
            s["detailNormalMap"] = self.detail_normal
            s["detailNormalMapStrength"] = _r(self.detail_strength)
            s["detailScale"] = list(self.detail_scale)
            s["normalDetailMapUseUV"] = 1
        if self.detail_map:
            s["detailMap"] = self.detail_map
            s["detailMapUseUV"] = 1
            s["detailScale"] = list(self.detail_scale)
        s.update(self.extra)
        return s

    def to_json(self):
        m = OrderedDict()
        m["name"] = self.name
        m["mapTo"] = self.name
        m["class"] = "Material"
        m["Stages"] = [self.stage0(), {}, {}, {}]
        if self.kind in ("glass", "glass_dmg"):
            m["castShadows"] = False
            m["translucent"] = True
            m["translucentBlendOp"] = "PreMulAlpha"
            m["translucentRecvShadows"] = True
            if self.kind == "glass_dmg":
                m["alphaRef"] = 20
                m["alphaTest"] = True
        elif self.kind == "decal":
            m["translucent"] = True
            m["translucentRecvShadows"] = True
            m["translucentZWrite"] = True
        if self.double_sided:
            m["doubleSided"] = True
        m["dynamicCubemap"] = True
        m["materialTag0"] = "beamng"
        m["materialTag1"] = "vehicle"
        m["version"] = 1.5
        return m


def _r(v):
    return round(float(v), 4)


# ---------------------------------------------------------------------------
# registry
# ---------------------------------------------------------------------------
REGISTRY: "OrderedDict[str, Mat]" = OrderedDict()


def add(name, **kw):
    if name in REGISTRY:
        raise ValueError(f"material {name} defined twice")
    REGISTRY[name] = Mat(name, **kw)
    return REGISTRY[name]


def lights(owner, base, color, lens_n=None, nits_on=15000.0, nits_int=30000.0, emissive=(1, 1, 1), preview=None):
    """off / on / on_intense / dmg family for a glow-mapped lamp lens."""
    common = dict(owner=owner, color=color, rough=0.04, metal=0.0, clearcoat=1.0, normal_map=lens_n)
    add(base, **common, preview=preview)
    add(base + "_on", kind="emissive", emissive=emissive, nits=nits_on, **common)
    add(base + "_on_intense", kind="emissive", emissive=emissive, nits=nits_int, **common)
    add(base + "_dmg", owner=owner, color=tuple(c * 0.35 for c in color), rough=0.5,
        normal_map=tex(owner, f"{owner}_glass_dmg_nm.normal.png"))


def _define():
    # ===================== vehicle specific (S13) =====================
    o = "s13"
    add("s13_paint", owner=o, kind="paint", preview=(0.55, 0.03, 0.03, 1))
    add("s13_enginebay_paint", owner=o, kind="paint", preview=(0.50, 0.03, 0.03, 1))
    add("s13_trim_black", owner=o, color=(0.012, 0.012, 0.013), rough=0.55, detail_normal=BUILTIN["leather_grain"],
        detail_scale=(60, 60), detail_strength=0.25)
    add("s13_trim_gloss", owner=o, color=(0.008, 0.008, 0.009), rough=0.12, clearcoat=0.6)
    add("s13_rubber", owner=o, color=(0.008, 0.008, 0.008), rough=0.85)
    add("s13_glass", owner=o, kind="glass", color=(0.03, 0.04, 0.045), rough=0.0, metal=0.75, opacity=0.22,
        preview=(0.05, 0.07, 0.08, 0.25))
    add("s13_glass_dmg", owner=o, kind="glass_dmg", color=(1, 1, 1), rough=0.05, metal=0.75,
        base_map=tex(o, "s13_glass_dmg_b.color.png"), opacity_map=tex(o, "s13_glass_dmg_o.data.png"),
        normal_map=tex(o, "s13_glass_dmg_nm.normal.png"), preview=(0.6, 0.65, 0.68, 0.6))
    add("s13_gauge_glass", owner=o, kind="glass", color=(0.01, 0.01, 0.012), rough=0.0, metal=0.6, opacity=0.08,
        preview=(0.02, 0.02, 0.02, 0.08))
    lens_n = tex(o, "s13_lens_nm.normal.png")
    lights(o, "s13_lights", (0.85, 0.86, 0.88), lens_n, 15000, 30000, preview=(0.8, 0.82, 0.85, 1))
    lights(o, "s13_lights_red", (0.32, 0.005, 0.005), tex(o, "s13_tail_nm.normal.png"), 2500, 12000,
           emissive=(1.0, 0.04, 0.02), preview=(0.45, 0.01, 0.01, 1))
    lights(o, "s13_lights_amber", (0.45, 0.16, 0.0), tex(o, "s13_tail_nm.normal.png"), 12000, 14000,
           emissive=(1.0, 0.45, 0.02), preview=(0.6, 0.25, 0.0, 1))
    lights(o, "s13_lights_reverse", (0.75, 0.75, 0.76), tex(o, "s13_tail_nm.normal.png"), 9000, 9000,
           emissive=(1.0, 0.98, 0.94), preview=(0.75, 0.75, 0.76, 1))
    add("s13_headlight_chrome", owner=o, color=(0.9, 0.9, 0.9), rough=0.05, metal=1.0)
    add("s13_popup_housing", owner=o, color=(0.015, 0.015, 0.016), rough=0.6)
    add("s13_gauges", owner=o, color=(1, 1, 1), base_map=tex(o, "s13_gauges_b.color.png"), rough=0.6,
        preview_tex="vehicles/s13_240sx/textures/s13_gauges_b.color.png")
    add("s13_gauges_on", owner=o, kind="emissive", color=(1, 1, 1), base_map=tex(o, "s13_gauges_b.color.png"),
        emissive_map=tex(o, "s13_gauges_g.color.png"), emissive=(1, 1, 1), nits=220, rough=0.6)
    add("s13_needle_off", owner=o, color=(0.85, 0.12, 0.02), rough=0.4)
    add("s13_needle_on", owner=o, color=(0.85, 0.12, 0.02), rough=0.4, kind="emissive", emissive=(1.0, 0.25, 0.05), nits=300)
    add("s13_undercoat", owner=o, color=(0.025, 0.025, 0.027), rough=0.9, detail_normal=BUILTIN["leather_grain"],
        detail_scale=(25, 25), detail_strength=0.6)
    add("s13_interior_plastic", owner=o, color=(0.022, 0.022, 0.024), rough=0.72, detail_normal=BUILTIN["leather_grain"],
        detail_scale=(45, 45), detail_strength=0.6)
    add("s13_interior_plastic_light", owner=o, color=(0.06, 0.06, 0.065), rough=0.7, detail_normal=BUILTIN["leather_grain"],
        detail_scale=(45, 45), detail_strength=0.6)
    add("s13_carpet", owner=o, color=(0.03, 0.03, 0.032), rough=0.95, detail_normal=BUILTIN["carpet"], detail_scale=(30, 30),
        detail_strength=1.5)
    add("s13_headliner", owner=o, color=(0.30, 0.30, 0.30), rough=0.95, detail_normal=BUILTIN["headliner"],
        detail_scale=(35, 35), detail_strength=1.5)
    add("s13_seat_cloth", owner=o, color=(1, 1, 1), base_map=tex(o, "s13_seat_cloth_b.color.png"), rough=0.95,
        detail_normal=BUILTIN["headliner"], detail_scale=(60, 60), detail_strength=1.2,
        preview_tex="vehicles/s13_240sx/textures/s13_seat_cloth_b.color.png")
    add("s13_seat_leather", owner=o, color=(0.05, 0.045, 0.04), rough=0.55, detail_normal=BUILTIN["leather"],
        detail_scale=(50, 50))
    add("s13_doorcard", owner=o, color=(1, 1, 1), base_map=tex(o, "s13_seat_cloth_b.color.png"), rough=0.9,
        detail_normal=BUILTIN["headliner"], detail_scale=(50, 50), detail_strength=1.0,
        preview_tex="vehicles/s13_240sx/textures/s13_seat_cloth_b.color.png")
    add("s13_radio", owner=o, color=(1, 1, 1), base_map=tex(o, "s13_radio_b.color.png"), rough=0.5,
        preview_tex="vehicles/s13_240sx/textures/s13_radio_b.color.png")
    add("s13_hvac", owner=o, color=(1, 1, 1), base_map=tex(o, "s13_hvac_b.color.png"), rough=0.5,
        preview_tex="vehicles/s13_240sx/textures/s13_hvac_b.color.png")
    add("s13_badge_chrome", owner=o, color=(0.85, 0.85, 0.87), rough=0.06, metal=1.0)
    add("s13_badge_red", owner=o, color=(0.5, 0.02, 0.02), rough=0.2, clearcoat=1.0)
    add("s13_grille", owner=o, color=(0.01, 0.01, 0.011), rough=0.5)
    # glowMap keys: mesh material names that the game swaps for off/on/on_intense materials (not written to json)
    for key, like in (("s13_headlight", "s13_lights"), ("s13_taillight", "s13_lights_red"), ("s13_signal_L", "s13_lights_amber"),
                      ("s13_signal_R", "s13_lights_amber"), ("s13_reverselight", "s13_lights_reverse"),
                      ("s13_gaugeface", "s13_gauges"), ("s13_needle", "s13_needle_off")):
        ref = REGISTRY[like]
        add(key, owner=o, color=ref.color, rough=ref.rough, metal=ref.metal, clearcoat=ref.clearcoat, preview=ref.preview,
            preview_tex=ref.preview_tex, write=False)
    add("s13_tail_garnish", owner=o, color=(0.22, 0.004, 0.004), rough=0.05, clearcoat=1.0,
        normal_map=tex(o, "s13_tail_nm.normal.png"))

    # ===================== shared (s1x) =====================
    o = "s1x"
    add("s1x_metal_black", color=(0.018, 0.018, 0.019), rough=0.48, metal=0.0, clearcoat=0.2,
        detail_normal=tex(o, "s1x_cast_nm.normal.png"), detail_scale=(12, 12), detail_strength=0.3)
    add("s1x_metal_steel", color=(0.55, 0.55, 0.56), rough=0.32, metal=1.0,
        detail_normal=tex(o, "s1x_cast_nm.normal.png"), detail_scale=(12, 12), detail_strength=0.25)
    add("s1x_aluminium", color=(0.62, 0.62, 0.63), rough=0.42, metal=1.0,
        detail_normal=tex(o, "s1x_cast_nm.normal.png"), detail_scale=(10, 10), detail_strength=0.5)
    add("s1x_aluminium_polished", color=(0.9, 0.9, 0.91), rough=0.08, metal=1.0)
    add("s1x_rubber", color=(0.012, 0.012, 0.012), rough=0.88)
    add("s1x_chrome", color=(0.92, 0.92, 0.93), rough=0.03, metal=1.0)
    add("s1x_dark", color=(0.006, 0.006, 0.007), rough=0.6)
    add("s1x_plastic_black", color=(0.015, 0.015, 0.016), rough=0.55, detail_normal=BUILTIN["leather_grain"],
        detail_scale=(50, 50), detail_strength=0.3)
    for col, rgb in (("red", (0.55, 0.02, 0.02)), ("blue", (0.02, 0.12, 0.55)), ("yellow", (0.75, 0.5, 0.02)),
                     ("purple", (0.25, 0.03, 0.45)), ("black", (0.02, 0.02, 0.02)), ("green", (0.05, 0.35, 0.08))):
        add(f"s1x_spring_{col}", color=rgb, rough=0.3, clearcoat=0.6)
    add("s1x_rotor", color=(0.42, 0.42, 0.43), rough=0.38, metal=1.0, normal_map=tex(o, "s1x_rotor_nm.normal.png"))
    add("s1x_rotor_hat", color=(0.10, 0.10, 0.10), rough=0.7, metal=0.6)
    for col, rgb, r, m in (("raw", (0.25, 0.24, 0.23), 0.7, 0.7), ("black", (0.015, 0.015, 0.016), 0.35, 0.0),
                           ("red", (0.55, 0.015, 0.01), 0.25, 0.0), ("gold", (0.65, 0.42, 0.06), 0.3, 0.6)):
        add(f"s1x_caliper_{col}", color=rgb, rough=r, metal=m, clearcoat=0.5 if m < 0.5 else 0.0,
            detail_normal=tex(o, "s1x_cast_nm.normal.png"), detail_scale=(14, 14), detail_strength=0.4)
    add("s1x_engine_block", color=(0.16, 0.16, 0.165), rough=0.75, metal=0.7,
        detail_normal=tex(o, "s1x_cast_nm.normal.png"), detail_scale=(8, 8), detail_strength=0.8)
    add("s1x_engine_block_alu", color=(0.45, 0.45, 0.46), rough=0.6, metal=1.0,
        detail_normal=tex(o, "s1x_cast_nm.normal.png"), detail_scale=(8, 8), detail_strength=0.8)
    add("s1x_engine_cover_silver", color=(0.55, 0.55, 0.56), rough=0.35, metal=1.0, clearcoat=0.3)
    add("s1x_engine_cover_red", color=(0.45, 0.02, 0.02), rough=0.55, clearcoat=0.2,
        detail_normal=tex(o, "s1x_crinkle_nm.normal.png"), detail_scale=(30, 30), detail_strength=0.6)
    add("s1x_engine_cover_k20red", color=(0.55, 0.015, 0.015), rough=0.6, clearcoat=0.15,
        detail_normal=tex(o, "s1x_crinkle_nm.normal.png"), detail_scale=(40, 40), detail_strength=1.2)
    add("s1x_k20_manifold", color=(0.58, 0.58, 0.6), rough=0.45, metal=1.0,
        detail_normal=tex(o, "s1x_cast_nm.normal.png"), detail_scale=(10, 10), detail_strength=0.6)
    add("s1x_exhaust", color=(0.32, 0.3, 0.28), rough=0.6, metal=1.0,
        detail_normal=tex(o, "s1x_cast_nm.normal.png"), detail_scale=(10, 10), detail_strength=0.3)
    add("s1x_exhaust_hot", color=(0.18, 0.12, 0.09), rough=0.75, metal=0.8,
        detail_normal=tex(o, "s1x_cast_nm.normal.png"), detail_scale=(10, 10), detail_strength=0.6)
    add("s1x_header", color=(0.55, 0.45, 0.38), rough=0.3, metal=1.0)
    add("s1x_turbo_hot", color=(0.12, 0.09, 0.07), rough=0.75, metal=0.8,
        detail_normal=tex(o, "s1x_cast_nm.normal.png"), detail_scale=(14, 14), detail_strength=0.8)
    add("s1x_intercooler", color=(0.5, 0.5, 0.52), rough=0.4, metal=1.0, base_map=tex(o, "s1x_core_b.color.png"),
        normal_map=tex(o, "s1x_core_nm.normal.png"), preview_tex="vehicles/common/s1x_240sx/textures/s1x_core_b.color.png")
    add("s1x_radiator_core", color=(0.35, 0.35, 0.36), rough=0.5, metal=1.0, base_map=tex(o, "s1x_core_b.color.png"),
        normal_map=tex(o, "s1x_core_nm.normal.png"), preview_tex="vehicles/common/s1x_240sx/textures/s1x_core_b.color.png")
    add("s1x_filter_red", color=(0.5, 0.02, 0.02), rough=0.9, detail_normal=BUILTIN["headliner"], detail_scale=(60, 60))
    # wheels
    add("s1x_wheel_steel", color=(0.02, 0.02, 0.021), rough=0.4, clearcoat=0.4)
    add("s1x_wheel_silver", color=(0.6, 0.6, 0.62), rough=0.25, metal=1.0, clearcoat=1.0)
    add("s1x_wheel_polished", color=(0.92, 0.92, 0.93), rough=0.05, metal=1.0, clearcoat=1.0)
    add("s1x_wheel_bronze", color=(0.42, 0.28, 0.08), rough=0.3, metal=1.0, clearcoat=1.0)
    add("s1x_wheel_black", color=(0.012, 0.012, 0.013), rough=0.35, metal=0.0, clearcoat=0.8)
    add("s1x_wheel_white", color=(0.75, 0.75, 0.75), rough=0.3, clearcoat=1.0)
    add("s1x_wheel_gunmetal", color=(0.1, 0.1, 0.11), rough=0.3, metal=1.0, clearcoat=1.0)
    add("s1x_wheel_barrel", color=(0.7, 0.7, 0.72), rough=0.2, metal=1.0, clearcoat=0.5)
    add("s1x_wheel_cap", color=(0.02, 0.02, 0.02), rough=0.25, clearcoat=1.0)
    add("s1x_lugnut", color=(0.8, 0.8, 0.82), rough=0.1, metal=1.0)
    add("s1x_hubcap", color=(0.55, 0.56, 0.58), rough=0.3, metal=0.8, clearcoat=0.8)
    for key in ("street", "semi", "slick"):
        add(f"s1x_tire_{key}", color=(1, 1, 1), base_map=tex(o, f"s1x_tire_{key}_b.color.png"),
            normal_map=tex(o, f"s1x_tire_{key}_nm.normal.png"), rough=0.9 if key != "slick" else 0.75,
            preview_tex=f"vehicles/common/s1x_240sx/textures/s1x_tire_{key}_b.color.png")
    # interior shared
    add("s1x_steer_leather", color=(0.02, 0.02, 0.02), rough=0.55, detail_normal=BUILTIN["leather_grain"],
        detail_scale=(60, 60))
    add("s1x_steer_suede", color=(0.025, 0.025, 0.025), rough=0.95, detail_normal=BUILTIN["headliner"],
        detail_scale=(70, 70), detail_strength=1.5)
    add("s1x_steer_metal", color=(0.05, 0.05, 0.055), rough=0.25, metal=1.0)
    add("s1x_carbon", color=(0.32, 0.32, 0.32), rough=0.09, clearcoat=0.93, cc_rough=0.05,
        detail_map=BUILTIN["carbon_d"], detail_normal=BUILTIN["carbon_n"], detail_scale=(60, 60), detail_strength=0.77,
        preview=(0.03, 0.03, 0.03, 1))


_define()


# ---------------------------------------------------------------------------
# outputs
# ---------------------------------------------------------------------------
def by_owner(owner):
    return OrderedDict((n, m) for n, m in REGISTRY.items() if m.owner == owner)


def write_json(mod_root, owner, names=None):
    """Write <folder>/main.materials.json for an owner (optionally restricted to `names`)."""
    import json
    mats = OrderedDict((n, m) for n, m in by_owner(owner).items() if m.write)
    if names is not None:
        mats = OrderedDict((n, m) for n, m in mats.items() if n in names)
    out = OrderedDict((n, m.to_json()) for n, m in mats.items())
    folder = os.path.join(mod_root, FOLDERS[owner])
    os.makedirs(folder, exist_ok=True)
    fn = "main.materials.json" if owner != "s1x" else "s1x.materials.json"
    path = os.path.join(folder, fn)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(out, f, indent=2)
        f.write("\n")
    return path


def referenced_textures(names=None):
    """All texture game paths referenced by (a subset of) the registry."""
    out = set()
    for n, m in REGISTRY.items():
        if names is not None and n not in names:
            continue
        for st in m.to_json()["Stages"]:
            for k, v in st.items():
                if isinstance(v, str) and v.startswith("/"):
                    out.add(v)
    return out


def blender_material(name, mod_root=None):
    """Create/refresh a Principled preview material for a registry entry (requires bpy)."""
    import bpy
    m = REGISTRY.get(name)
    mat = bpy.data.materials.get(name) or bpy.data.materials.new(name)
    mat.use_nodes = True
    nt = mat.node_tree
    bsdf = nt.nodes.get("Principled BSDF")
    if m is None:
        bsdf.inputs["Base Color"].default_value = (1.0, 0.0, 1.0, 1.0)  # loud magenta: unregistered
        return mat
    rgba = m.preview or (*m.color, 1.0)
    if m.kind == "glass" and m.preview is None:
        rgba = (*m.color, m.opacity)
    bsdf.inputs["Base Color"].default_value = rgba[:3] + (1.0,)
    bsdf.inputs["Metallic"].default_value = m.metal if m.kind != "paint" else 0.2
    bsdf.inputs["Roughness"].default_value = m.rough if m.kind != "paint" else 0.25
    if "Coat Weight" in bsdf.inputs:
        bsdf.inputs["Coat Weight"].default_value = 1.0 if m.kind == "paint" else m.clearcoat
        bsdf.inputs["Coat Roughness"].default_value = 0.03
    if rgba[3] < 1.0:
        bsdf.inputs["Alpha"].default_value = rgba[3]
    if m.kind == "emissive" and m.emissive and m.nits > 1000:
        bsdf.inputs["Emission Color"].default_value = (*m.emissive, 1.0)
        bsdf.inputs["Emission Strength"].default_value = 4.0
    if m.preview_tex and mod_root:
        p = os.path.join(mod_root, m.preview_tex)
        if os.path.exists(p):
            img = bpy.data.images.load(p, check_existing=True)
            tn = nt.nodes.new("ShaderNodeTexImage")
            tn.image = img
            nt.links.new(tn.outputs["Color"], bsdf.inputs["Base Color"])
    mat.diffuse_color = rgba
    return mat
